extends: default
ignore: |
  .git
  .venv
rules:
  document-start: disable
  truthy: disable
  comments:
    level: error
  comments-indentation:
    level: error
  line-length:
    max: 110
  quoted-strings:
    quote-type: double
    required: false
